### ISSUE TITLE
config.conf["UIA"]["useInMSWordWhenAvailable"] is no longer available

### ISSUE THREAD

**Issue by cary-rowen** [paulber19/wordAccessEnhancementNVDAAddon#3]
Hi,

You used config.conf["UIA"]["useInMSWordWhenAvailable"] to check for UIA this will be broken in 2022.1.

**Comment by paulber19** [comment]
Hi Rowen.
Thank you very much for the information.
This has already been fixed in the development version in preparation.
Best regards.
Paul.

**Comment by cary-rowen** [comment]
This is great
